import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const panel = readFileSync(new URL('../src/SeriesCastPanel.tsx', import.meta.url), 'utf8')
const narrationPanel = readFileSync(new URL('../src/NarrationPanel.tsx', import.meta.url), 'utf8')
const app = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')
const voiceProfilesPanel = readFileSync(new URL('../src/CharacterVoiceProfilesPanel.tsx', import.meta.url), 'utf8')
const characterLibraryPage = readFileSync(new URL('../src/pages/CharacterLibraryPage.tsx', import.meta.url), 'utf8')
const appLayout = readFileSync(new URL('../src/AppLayout.tsx', import.meta.url), 'utf8')
const api = readFileSync(new URL('../src/api.ts', import.meta.url), 'utf8')
const serverVoiceCatalog = readFileSync(new URL('../../StoryVoice.Infrastructure/Persistence/SeriesVoiceCatalogOptions.cs', import.meta.url), 'utf8')
const apiSettings = readFileSync(new URL('../../StoryVoice.Api/appsettings.json', import.meta.url), 'utf8')

test('系列配音控制台固定使用 owner-scoped series、角色與 alias API', () => {
  assert.match(panel, /\/api\/series\/voice-options/)
  assert.match(panel, /\/api\/series\/\$\{details\.id\}\/books/)
  assert.match(panel, /\/api\/series\/\$\{details\.id\}\/characters/)
  assert.match(panel, /\/aliases/)
  assert.match(panel, /固定角色聲線/)
  assert.doesNotMatch(panel, /fuzzy|模糊比對/i)
})

test('聲線選擇以 provider 與 voice 複合 identity 區分，送出時還原 API 欄位', () => {
  assert.match(panel, /const voiceKey = \(voice: VoiceOption\) => `\$\{voice\.provider\}\\n\$\{voice\.voice\}`/)
  assert.match(panel, /voiceKey\(option\) === narratorVoiceKey/)
  assert.match(panel, /voiceKey\(option\) === characterVoiceKey/)
  assert.match(panel, /narratorProvider: selectedVoice\.provider/)
  assert.match(panel, /narratorVoice: selectedVoice\.voice/)
  assert.match(panel, /voiceProvider: selectedVoice\.provider/)
  assert.match(panel, /voice: selectedVoice\.voice/)
  assert.match(panel, /value=\{voiceKey\(option\)\}/)
  assert.match(panel, /voiceLabel\(details\.narratorProvider, details\.narratorVoice, voiceOptions\)/)
  assert.match(panel, /voiceLabel\(character\.voiceProvider, character\.voice, voiceOptions\)/)
  assert.doesNotMatch(panel, /option\.voice === narratorVoice/)
  assert.doesNotMatch(panel, /option\.voice === characterVoice/)
})

test('角色庫自訂聲線仍固定解析 3wa provider，不出現在手動固定聲線清單', () => {
  assert.match(panel, /const CUSTOM_VOICE_PROVIDER = '3wa-voxcpm2'/)
  assert.match(panel, /voiceOptions\.find\(\(option\) => option\.provider === CUSTOM_VOICE_PROVIDER\)/)
  assert.match(panel, /details\.narratorProvider === CUSTOM_VOICE_PROVIDER/)
  assert.match(panel, /option\.provider === EDGE_VOICE_PROVIDER/)
  assert.match(panel, /manualCharacterVoiceOptions\.map/)
  assert.match(panel, /改用 Edge fallback/)
  assert.match(panel, /characterProfileId: usingLibraryCharacter \? selectedCharacterProfileId : null/)
})

test('手動角色聲線受系列 narrator provider 限制，切換系列會清除不相容選擇', () => {
  assert.match(panel, /option\.provider === details\.narratorProvider/)
  assert.match(panel, /manualCharacterVoiceOptions\.some\(\(option\) => voiceKey\(option\) === current\)/)
  assert.match(panel, /manualCharacterVoiceOptions\.find\(\(option\) => voiceKey\(option\) === characterVoiceKey\)/)
  assert.match(panel, /setSelectedCharacterProfileId\(''\)/)
  assert.doesNotMatch(panel, /voiceOptions\.find\(\(option\) => voiceKey\(option\) === characterVoiceKey\)/)
})

test('VoAI 系列禁止 3wa 角色庫並明示伺服器試音，建立系列仍可由完整聲線清單選 VoAI', () => {
  assert.match(panel, /const VOAI_VOICE_PROVIDER = 'voai'/)
  assert.match(panel, /這個系列使用 VoAI；不可混用 3wa 角色庫自訂聲線/)
  assert.match(panel, /VoAI 聲線無法由瀏覽器 speechSynthesis 模擬/)
  assert.match(panel, /disabled=\{details\.narratorProvider === VOAI_VOICE_PROVIDER\}/)
  assert.match(panel, /voiceOptions\.map\(\(option\) => <option key=\{voiceKey\(option\)\} value=\{voiceKey\(option\)\}/)
  assert.match(panel, /narratorProvider: selectedVoice\.provider/)
  assert.match(panel, /narratorVoice: selectedVoice\.voice/)
})

test('BlueMagpie 保留伺服器固定句試音，正式系列聲線另走原子設定與 admission gate', () => {
  assert.match(panel, /const BLUE_MAGPIE_PROVIDER = 'bluemagpie'/)
  assert.match(panel, /female_voice/)
  assert.match(panel, /hung_yi_lee/)
  assert.match(panel, /fetchBlob\('\/api\/series\/voice-preview'/)
  assert.match(panel, /body: \{ provider: BLUE_MAGPIE_PROVIDER, voice: requestedVoice \}/)
  assert.match(panel, /不傳送小說正文、不呼叫 VoAI/)
  assert.match(panel, /URL\.createObjectURL\(audio\)/)
  assert.match(panel, /URL\.revokeObjectURL\(blueMagpiePreviewUrl\)/)
  assert.match(panel, /blueMagpiePreviewRequest\.current\?\.abort\(\)/)
  assert.match(panel, /signal: controller\.signal/)
  assert.match(panel, /setBlueMagpiePreviewUrl\(null\)/)
  assert.match(panel, /<audio autoPlay/)
  assert.match(api, /export async function fetchBlob/)
  assert.match(api, /return response\.blob\(\)/)
  assert.match(panel, /\/api\/series\/\$\{details\.id\}\/voices/)
  assert.match(panel, /儲存整系列聲線/)
  assert.match(panel, /mixed-provider/)
  assert.match(panel, /只有內建女聲與男聲兩種 timbre/)
  assert.match(panel, /rate、pitch、volume 重設為中性/)
  assert.match(panel, /下一次 staged rebuild/)
  assert.match(panel, /不會立刻替換既有已啟用音訊/)
  assert.match(panel, /私人自架使用/)
  assert.match(serverVoiceCatalog, /CharacterVoiceProviders\.BlueMagpie/)
  assert.match(serverVoiceCatalog, /female_voice/)
  assert.match(serverVoiceCatalog, /hung_yi_lee/)
  const settings = JSON.parse(apiSettings)
  assert.equal(settings.BlueMagpie.FormalNarrationEnabled, false)
  assert.equal(settings.MultiCharacterNarration.ProviderVersions.bluemagpie, 'bm1-d2d7ef3e81456915eb7a3cfe2446a9f19417c21b')
  assert.equal(settings.SeriesVoiceCatalog.Voices.filter((voice) => voice.Provider === 'bluemagpie').length, 2)
})

test('整系列聲線切換送出完整角色集合，依旁白 provider 限制逐角選項', () => {
  assert.match(panel, /configuredNarratorVoiceKey/)
  assert.match(panel, /configuredCharacterVoiceKeys/)
  assert.match(panel, /option\.provider === configuredNarratorVoice\.provider/)
  assert.match(panel, /details\.characters\.map\(\(character\) => \{/)
  assert.match(panel, /characterId: character\.id/)
  assert.match(panel, /narratorProvider: configuredNarratorVoice\.provider/)
  assert.match(panel, /narratorVoice: configuredNarratorVoice\.voice/)
  assert.match(panel, /method: 'PUT'/)
})

test('staged rebuild 狀態以既有系列成員解析書名，不假設 rebuild API 回傳額外 bookTitle', () => {
  assert.match(panel, /members: Array<\{ id: string; bookId: string; status: string/)
  assert.doesNotMatch(panel, /members: Array<\{ id: string; bookTitle: string/)
  assert.match(panel, /details\.books\.find/)
})

test('書庫朗讀面板不再建立單聲線工作，而是導向系列配音流程', () => {
  assert.match(narrationPanel, /\/series/)
  assert.match(narrationPanel, /多角色系列配音/)
  assert.doesNotMatch(narrationPanel, /function createNarration/)
})

test('App 可開啟系列配音控制台', () => {
  assert.match(app, /path="\/series"/)
  assert.match(app, /SeriesCastPanel/)
})

test('角色分析套用後可由 query string 直接開啟指定系列', () => {
  assert.match(panel, /useSearchParams/)
  assert.match(panel, /searchParams\.get\('seriesId'\)/)
  assert.match(panel, /item\.id === requestedSeriesId/)
})

test('系列配音控制台每個角色都可以展開自訂聲線工作室', () => {
  assert.match(panel, /import { CharacterVoiceProfilesPanel } from '\.\/CharacterVoiceProfilesPanel'/)
  assert.match(panel, /<CharacterVoiceProfilesPanel/)
  assert.match(panel, /自訂聲線/)
})

test('自訂聲線工作室固定使用 owner-scoped 角色庫 voice-profiles API，涵蓋基礎與四種情境聲線', () => {
  assert.match(voiceProfilesPanel, /\/api\/character-profiles\/\$\{characterProfileId\}\/voice-profiles/)
  assert.doesNotMatch(voiceProfilesPanel, /\/api\/series\/.*\/characters\/.*\/voice-profiles/)
  assert.doesNotMatch(voiceProfilesPanel, /sceneCode: 'neutral'/)
  assert.match(voiceProfilesPanel, /sceneCode: 'nervous'/)
  assert.match(voiceProfilesPanel, /sceneCode: 'happy'/)
  assert.match(voiceProfilesPanel, /sceneCode: 'angry'/)
  assert.match(voiceProfilesPanel, /sceneCode: 'sad'/)
  assert.match(voiceProfilesPanel, /self_recorded/)
  assert.match(voiceProfilesPanel, /explicit_permission/)
  assert.match(voiceProfilesPanel, /licensed_voice/)
  assert.doesNotMatch(voiceProfilesPanel, /fuzzy|模糊比對/i)
})

test('Design 聲線由 owner-scoped slot endpoint 建立並送出 CSRF 與 voicePrompt', () => {
  assert.match(voiceProfilesPanel, /const slotMode = mode\[slotKey\] \?\? 'Design'/)
  assert.match(voiceProfilesPanel, /`\$\{slotPath\(characterProfileId, sceneCode\)\}\/design`/)
  assert.match(voiceProfilesPanel, /method: 'POST'/)
  assert.match(voiceProfilesPanel, /csrfToken,/)
  assert.match(voiceProfilesPanel, /body: \{ voicePrompt: text \}/)
  assert.match(voiceProfilesPanel, /文字設計模式不需要等待處理/)
})

test('系列角色只有連結角色庫時才顯示自訂聲線，且加入角色時可以選角色庫既有角色', () => {
  assert.match(panel, /character\.characterProfileId &&/)
  assert.match(panel, /characterProfileId={character\.characterProfileId}/)
  assert.match(panel, /\/api\/character-profiles/)
  assert.match(panel, /selectedCharacterProfileId/)
  assert.match(panel, /characterProfileId: usingLibraryCharacter \? selectedCharacterProfileId : null/)
})

test('既有系列角色可以透過專用原子 API 後補或解除角色庫連結', () => {
  assert.match(panel, /characterProfileSelections/)
  assert.match(panel, /saveCharacterProfileLink/)
  assert.match(panel, /\/api\/series\/\$\{details\.id\}\/characters\/\$\{character\.id\}\/character-profile/)
  assert.match(panel, /body: \{ characterProfileId: characterProfileId \|\| null \}/)
  assert.match(panel, /method: 'PUT'/)
  assert.match(panel, /setDetails\(updated\)/)
  assert.match(panel, /setBatch\(null\)/)
  assert.match(panel, /setFormState\('loading'\)/)
  assert.match(panel, /setFormState\('idle'\)/)
  assert.match(panel, /目前固定聲線與已啟用音訊不變/)
  assert.match(panel, /儲存單角連結/)
  assert.match(panel, /不連結角色庫（保留目前固定聲線）/)
})

test('同系列中已被其他角色使用的角色庫 identity 會停用，跨系列共用則有明確提示', () => {
  assert.match(panel, /findCharacterProfileLinkOwner/)
  assert.match(panel, /const unavailable = Boolean\(linkedBy\) \|\| \(!profile\.isActive && !isCurrentProfile\)/)
  assert.match(panel, /<option disabled=\{unavailable\}/)
  assert.match(panel, /已連結：\$\{linkedBy\.canonicalName\}/)
  assert.match(panel, /系統允許跨系列共用角色庫角色/)
  assert.match(panel, /同一系列中已被另一角色連結的選項會停用/)
  assert.match(panel, /libraryCharacterAlreadyLinked/)
  assert.match(panel, /這個角色庫角色已停用或已被本系列使用/)
})

test('角色管理頁面走 owner-scoped 角色庫 API，並串接自訂聲線工作室', () => {
  assert.match(characterLibraryPage, /\/api\/character-profiles/)
  assert.match(characterLibraryPage, /<CharacterVoiceProfilesPanel/)
  assert.match(characterLibraryPage, /canonicalName/)
  assert.match(characterLibraryPage, /avatar/)
  assert.doesNotMatch(characterLibraryPage, /fuzzy|模糊比對/i)
})

test('App 與主導覽都能開啟角色管理頁面', () => {
  assert.match(app, /path="characters"/)
  assert.match(app, /CharacterLibraryPage/)
  assert.match(appLayout, /to="\/characters"/)
})

test('聲線卡片顯示字數與時長，並提供可重播與下載的即時試講', () => {
  assert.match(voiceProfilesPanel, /referenceAudioDurationSeconds/)
  assert.match(voiceProfilesPanel, /字數/)
  assert.match(voiceProfilesPanel, /formatDuration/)
  assert.match(voiceProfilesPanel, /\/preview/)
  assert.match(voiceProfilesPanel, /playPreview/)
  assert.match(voiceProfilesPanel, /credentials: 'same-origin'/)
  assert.match(voiceProfilesPanel, /'Content-Type': 'application\/json'/)
  assert.match(voiceProfilesPanel, /'X-CSRF-TOKEN': csrfToken/)
  assert.match(voiceProfilesPanel, /body: JSON\.stringify\(\{ text \}\)/)
  assert.match(voiceProfilesPanel, /response\.blob\(\)/)
  assert.match(voiceProfilesPanel, /URL\.createObjectURL\(blob\)/)
  assert.match(voiceProfilesPanel, /<audio/)
  assert.match(voiceProfilesPanel, /controls/)
  assert.match(voiceProfilesPanel, /download=\{currentPreview\.fileName\}/)
  assert.match(voiceProfilesPanel, /下載試音/)
  assert.match(voiceProfilesPanel, /safeDownloadFileNamePart/)
  assert.match(voiceProfilesPanel, /codePointAt/)
  assert.match(voiceProfilesPanel, /\[<>:"\/\\\\\|\?\*\]/)
})

test('試音 Blob URL 在取代、播放錯誤與 unmount 時都會釋放', () => {
  assert.match(voiceProfilesPanel, /const previousAudio = previewAudioRef\.current/)
  assert.match(voiceProfilesPanel, /if \(previousAudio\) URL\.revokeObjectURL\(previousAudio\.url\)/)
  assert.match(voiceProfilesPanel, /request\?\.controller\.abort\(\)/)
  assert.match(voiceProfilesPanel, /const audio = previewAudioRef\.current[\s\S]*previewAudioRef\.current = null[\s\S]*if \(audio\) URL\.revokeObjectURL\(audio\.url\)/)
  assert.match(voiceProfilesPanel, /onError=\{\(\) => releasePreviewAfterError\(currentPreview\.url\)\}/)
  assert.match(voiceProfilesPanel, /function releasePreviewAfterError\(url: string\)[\s\S]*URL\.revokeObjectURL\(current\.url\)/)
  assert.match(voiceProfilesPanel, /if \(controller\.signal\.aborted\) \{[\s\S]*URL\.revokeObjectURL\(url\)/)
})

test('角色 A 切到 B 再切回 A 也不會重顯已 revoke 的試音狀態', () => {
  assert.match(voiceProfilesPanel, /useEffect\(\(\) => \{\s*setPreviewAudio\(null\)\s*setPreviewing\(null\)\s*return \(\) => \{[\s\S]*\}\s*\}, \[characterProfileId\]\)/)
  assert.match(voiceProfilesPanel, /previewAudio\?\.characterProfileId === characterProfileId/)
  assert.match(voiceProfilesPanel, /previewing\?\.characterProfileId === characterProfileId/)
})

test('刪除目前有試音或正在合成的 profile 會立即中止並釋放', () => {
  assert.match(voiceProfilesPanel, /function releasePreviewForProfile\(profileId: string\)/)
  assert.match(voiceProfilesPanel, /request\?\.characterProfileId === characterProfileId && request\.profileId === profileId/)
  assert.match(voiceProfilesPanel, /request\.controller\.abort\(\)/)
  assert.match(voiceProfilesPanel, /current\?\.characterProfileId !== characterProfileId \|\| current\.profileId !== profileId/)
  assert.match(voiceProfilesPanel, /URL\.revokeObjectURL\(current\.url\)/)
  assert.match(voiceProfilesPanel, /async function remove\(profile: VoiceProfile\) \{\s*releasePreviewForProfile\(profile\.id\)\s*setBusySlot\(profile\.id\)[\s\S]*method: 'DELETE'/)
})

test('切換角色時會清空舊 profiles、中止舊 GET，並拒絕晚到回應覆蓋新角色', () => {
  assert.match(voiceProfilesPanel, /fetchJson<VoiceProfile\[]>\(basePath\(requestedCharacterProfileId\), \{ signal \}\)/)
  assert.match(voiceProfilesPanel, /loadGenerationRef\.current !== requestedGeneration/)
  assert.match(voiceProfilesPanel, /currentCharacterProfileIdRef\.current !== requestedCharacterProfileId/)
  assert.match(voiceProfilesPanel, /setProfilesState\(\{ characterProfileId: requestedCharacterProfileId, items: list \}\)/)
  assert.match(voiceProfilesPanel, /const profiles = profilesState\?\.characterProfileId === characterProfileId \? profilesState\.items : null/)
  assert.match(voiceProfilesPanel, /loadGenerationRef\.current \+= 1\s*const controller = new AbortController\(\)\s*setProfilesState\(null\)\s*void load\(controller\.signal\)/)
  assert.match(voiceProfilesPanel, /return \(\) => \{\s*loadGenerationRef\.current \+= 1\s*controller\.abort\(\)/)
  assert.match(voiceProfilesPanel, /catch \(error\) \{\s*if \(signal\?\.aborted[\s\S]*currentCharacterProfileIdRef\.current !== requestedCharacterProfileId\) return\s*setMessage/)
})

test('系列配音控制台可以設定視角角色，讓第一人稱自述對白自動歸給主角', () => {
  assert.match(panel, /\/api\/series\/\$\{details\.id\}\/point-of-view-character/)
  assert.match(panel, /視角角色（第一人稱敘事者）/)
  assert.match(panel, /pointOfViewCharacterId/)
  assert.match(panel, /method: 'PUT'/)
})

test('系列可切換獨立旁白或視角角色內心敘事，並讓既有草稿與 staged batch 失效', () => {
  assert.match(panel, /type NarrativeVoiceMode = 'IndependentNarrator' \| 'PointOfViewInnerMonologue'/)
  assert.match(panel, /narrativeVoiceMode: NarrativeVoiceMode/)
  assert.match(panel, /\/api\/series\/\$\{details\.id\}\/narrative-voice/)
  assert.match(panel, /body: \{\s*mode,\s*pointOfViewCharacterId: details\.pointOfViewCharacterId,/)
  assert.match(panel, /setDetails\(updated\)\s*setBatch\(null\)/)
  assert.match(panel, /逐章說話者草稿需要重新建立，目前已啟用音訊不變/)
  assert.match(panel, /正文敘事聲線/)
  assert.match(panel, /視角角色內心獨白/)
})

test('視角角色內心敘事必須先指定 POV，啟用後不能從視角選擇器清空', () => {
  assert.match(panel, /mode === 'PointOfViewInnerMonologue' && !details\.pointOfViewCharacterId/)
  assert.match(panel, /請先選擇視角角色，才能啟用視角角色內心敘事/)
  assert.match(panel, /!characterId && details\.narrativeVoiceMode === 'PointOfViewInnerMonologue'/)
  assert.match(panel, /disabled=\{details\.narrativeVoiceMode === 'PointOfViewInnerMonologue'\} value=""/)
  assert.match(panel, /<option disabled=\{!details\.pointOfViewCharacterId\} value="PointOfViewInnerMonologue"/)
})

test('角色管理頁面提供啟用狀態切換、摘要卡片、重設按鈕、試講與任務紀錄分頁', () => {
  assert.match(characterLibraryPage, /isActive/)
  assert.match(characterLibraryPage, /'activate'/)
  assert.match(characterLibraryPage, /'deactivate'/)
  assert.match(characterLibraryPage, /基礎聲線狀態/)
  assert.match(characterLibraryPage, /情境聲線數量/)
  assert.match(characterLibraryPage, /樣本語料時數/)
  assert.match(characterLibraryPage, /最近任務狀態/)
  assert.match(characterLibraryPage, /resetForm/)
  assert.match(characterLibraryPage, /'preview'/)
  assert.match(characterLibraryPage, /'tasks'/)
  assert.match(characterLibraryPage, /copyId/)
  assert.match(characterLibraryPage, /AI 輔助生成尚未提供/)
})
